title: John Doe # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Rising Sophomore at University of Michigan Ann Arbor. Currently majoring in Data Science.
  <br><br>
  I enjoy using programming to create unique solutions. Previous experience include coding in R, Python, Java, C++ and applying Large-Scale Molecular Dyamics to construct high-fidelity models.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
