title: Wenjin(Jack) Yu 
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Current Sophomore at University of Michigan Ann Arbor. Pursuing a dual degree in Business Administration and Data Science.
  <br><br>
  I enjoy using programming to create unique solutions and come up with data-driven decisions. My recent intern experience is working as an Entrepreneur Fellows at Scoutible. Previous experience include coding in R, Python, Java, C++ and applying Large-Scale Atomic/ Molecular Dyamics to construct high-fidelity models.
  <br><br>
  <a href="https://www.linkedin.com/in/wenjin-jack-yu-0714/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

