title: Wenjin(Jack) Yu # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/wenjin-jack-yu-0714/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

